### ISSUE TITLE
Persist chat on window refresh

### ISSUE THREAD

**Issue by iamvishal345** [manuelalferez/chatcus#28]
@manuelalferez 
I would like to work on adding feature to store chat into browser's storage so that if user refreshes the page the chat will persist.
I am thinking to leverage indexed DB API for that. Also clear that chat when user closes the chat box or navigate to other page.

**Comment by iamvishal345** [comment]
@manuelalferez  In our current webpack config we need to add babel packages for using async await. So I think instead of changing current config we should migrate to use vite by merging #26 PR.  We just need to figure out why the build is failing. Other changes I have tested locally and everything is working fine

**Comment by iamvishal345** [comment]
@manuelalferez It is working but first we need to know why the build is failing.

**Comment by iamvishal345** [comment]
> Solved. #26 is now merged.

Some recent changes are lost due to this merge

**Comment by iamvishal345** [comment]
Let me try this approach

**Comment by gitwikc** [comment]
This issue is addressed in PR #43 so this issue can be closed when it's merged
