### ISSUE TITLE
Profile picture feature not working

### ISSUE THREAD

**Issue by manuelalferez** [manuelalferez/chatcus#33]
@gitwikc I merged your pull request #22, but it's not charging the URL image like it should. Is there any aspect to have in mind?

**Comment by gitwikc** [comment]
Ok. Did you deploy the server side code to heroku? Because it SHOULD, in theory work perfectly if:
1. The client side code deploys
2. The server side code also deploys

Since the server code was altered for the profile picture choosing feature, it is IMPORANT to deploy both sides

**Comment by manuelalferez** [comment]
> ![image](https://user-images.githubusercontent.com/60361305/137495748-c7b3d4ca-9dde-46c9-b70f-6addcb9f5d25.png) Sometimes this error shows up. But after some time it starts working again. Maybe heroku doesn't keep the server up and running 24x7? I've experienced this issue even with previous version of the app, where it won't load for some time then all of a sudden everything's fine and it works.
> 
> Also how about we change the Heroku github repo back to the main repo and try [this method](https://jtway.co/deploying-subdirectory-projects-to-heroku-f31ed65f3f2)?

Oh, thanks for that reference. I will be a little busy this days, I won't be more free until the weekend. Let me know if you need something.

**Comment by manuelalferez** [comment]
Actual version on Heroku is not working @gitwikc
